---
# tasks file for cassandra
- name: Configure Cassandra SecurityContextConstraints
  kubernetes.core.k8s:
    src: ./scc.yaml
    state: present

- name: Configure k8ssandra chart repository
  kubernetes.core.helm_repository:
    name: k8ssandra
    repo_url: "https://helm.k8ssandra.io/stable"

- name: Configure Cassandra Operator
  kubernetes.core.helm:
    name: cass-operator
    chart_ref: k8ssandra/cass-operator
    chart_version: 0.40.0
    release_namespace: instana-cassandra
    create_namespace: true
    values:
      securityContext:
        runAsGroup: 999
        runAsUser: 999

- name: Wait for Cassandra Operator
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    label_selectors:
      - app.kubernetes.io/instance=cass-operator
    namespace: instana-cassandra
    wait_sleep: 10
    wait_timeout: 720

- name: Configure Cassandra Datastore
  kubernetes.core.k8s:
    template: ./datacenter-custom-registry.j2
    namespace: instana-cassandra
    state: present

- name: Wait for last Cassandra Pod
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    label_selectors:
      - statefulset.kubernetes.io/pod-name=instana-cassandra-default-sts-2
    namespace: instana-cassandra
    wait_sleep: 10
    wait_timeout: 1080
