---
# tasks file for credentials
- name: Save Initial Admin credentials
  shell: |
    printf "Console URL:\n%s\n" "$(oc get route openshift-gitops-server -n openshift-gitops -o jsonpath='{"https://"}{.spec.host}{"\n"}')" > ./provided-credentials
    {
      printf "\nUsername: admin\n"
      printf "\nPassword (for admin user only):\n%s\n" "$(oc extract secret/openshift-gitops-cluster -n openshift-gitops --keys="admin.password" --to=-)"
    }  >> ./provided-credentials